[package]
name = "git-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.101"
clap_derive = { version = "4.0.0-rc.1" }
clap = { version = "4.5.57", features = ["derive"] }
flate2 = "1.1.9"
sha1 = "0.10.6"
hex = "0.4.3"
